# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e7cc6fcc6ca7391a52b7c8523d8eba076c431605c07e66cd2b8e43ae216fb4a804338c86ec3064369825f904c5d7dad38df875967fdce6f695079a571ea566bc

test:
  secret_key_base: fca3b3d7e034b8899a42e7e02c14aad9514b066660e44e9b2f929dec6c30210ce85c924e514e115c895117a1a3ad960cc3f2cfc45ae08027f8036b209c106507

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
